-- db/schema.sql
--
-- Canonical, current-state baseline for the CWL Hub database.
--
-- This file is a SNAPSHOT, not a migration — it describes what the schema
-- IS, verified directly against Neon via information_schema.columns and
-- pg_constraint on 2026-06-21, not what any past migration script intended.
-- It supersedes schema.sql (the original Tier 6 foundation file) and
-- schema-tier7.sql (the assigned_clan ALTER TABLE) as the source of truth —
-- both of those are now historical and can be treated as already applied.
--
-- Going forward: do NOT edit this file in place for schema changes.
-- Add a new, sequentially numbered file under db/migrations/ instead
-- (e.g. db/migrations/002_add_status_column.sql), and apply it to Neon
-- in the SAME commit/deploy as the code that depends on it. This file
-- gets regenerated/updated only as a periodic "flatten migrations into
-- a fresh baseline" exercise, not as the everyday change mechanism.
--
-- Verified against live Neon (2026-06-21):
--   - information_schema.columns for accounts, pool_entries
--   - pg_constraint for both tables (PK, FK, UNIQUE, NOT NULL)

-- Verified CoC accounts. One row per player tag, ever. owner_secret is a
-- random token stored in the signer's browser cookie — it links an account
-- to "whoever verified it" without storing any personal identity, and is
-- never exposed in any admin-facing view or API response.
--
-- verified_at semantics (resolved 2026-06-21, previously ambiguous):
-- DEFAULT now() fires once at row creation only. upsertAccount's
-- ON CONFLICT DO UPDATE SET never touches verified_at — only player_name
-- and owner_secret are updated on re-verification. So this column tracks
-- "first ever verified," NOT "most recently verified," despite
-- getAccountsByOwner ordering by it to show "most recent" first. If
-- true most-recent ordering is ever needed, upsertAccount's ON CONFLICT
-- clause must be changed to also set verified_at = now() — that has not
-- been done as of this baseline.
CREATE TABLE IF NOT EXISTS accounts (
  player_tag   TEXT PRIMARY KEY,
  player_name  TEXT NOT NULL,
  owner_secret TEXT NOT NULL,
  verified_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS accounts_owner_secret_idx ON accounts (owner_secret);

-- Seasonal pool membership. A player_tag can appear once per season —
-- re-joining a later season is a fresh row, not an update, so history of
-- who signed up each season is preserved for free.
--
-- assigned_clan (added via schema-tier7.sql, confirmed live in Neon as of
-- this baseline): nullable, no DEFAULT. NULL = still in the unassigned
-- pool; non-NULL = assigned to that clan. Set exclusively by
-- lib/pool.js's markAssigned(playerTag, season, clan).
--
-- joined_at: written automatically via DEFAULT now() on INSERT. Currently
-- referenced only by the superseded getPoolForSeason — not read by any
-- live code path as of this baseline, but kept since it's harmless and
-- may be useful for future "time in pool" reporting.
CREATE TABLE IF NOT EXISTS pool_entries (
  id            SERIAL PRIMARY KEY,
  player_tag    TEXT NOT NULL REFERENCES accounts (player_tag),
  season        TEXT NOT NULL,
  joined_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  assigned_at   TIMESTAMPTZ,
  assigned_clan TEXT,
  UNIQUE (player_tag, season)
);

CREATE INDEX IF NOT EXISTS pool_entries_season_idx ON pool_entries (season);

-- ── Verified constraints (live Neon, 2026-06-21) ─────────────────────────
-- accounts_pkey                       PRIMARY KEY (player_tag)
-- pool_entries_pkey                   PRIMARY KEY (id)
-- pool_entries_player_tag_season_key  UNIQUE (player_tag, season)
-- pool_entries_player_tag_fkey        FOREIGN KEY (player_tag) REFERENCES accounts(player_tag)
-- All TEXT/TIMESTAMPTZ columns listed above are NOT NULL except
-- pool_entries.assigned_at and pool_entries.assigned_clan, which are
-- nullable by design (unassigned state).
